name: Kotlin CI

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      ## Actual task
      - name: Check with Gradle
        run: ./gradlew assemble test --no-daemon --stacktrace --continue
        # Decoder:
        #    --continue: Run all checks, even if some fail.
        #    test: unit tests
        #    apiCheck: binary compatibility
        #    jmhJar: Build the JMH benchmarks to verify, but don't run them